version: '3.8'

services:
  db:
    image: postgres
    ports:
            - "5432:5432"
    environment:
            POSTGRES_PASSWORD: postgres

  backend:
    platform: linux/x86_64
    container_name: django-react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    tty: true
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - db

  front:
    build:
      context: .
      dockerfile: Dockerfile_react
    restart: always
    volumes:
      - ./node:/usr/src/app:cached
    command: sh -c "cd django_front && yarn start"
    ports:
      - "3000:3000"
